language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install -U pytest pytest-cov
  - pip install coveralls
  - pip install sphinx
  - python setup.py build_sphinx
install:
  - pip install pytest flaky .
script:
  - py.test -s -v --cov=convoys .
after_success:
  - coveralls
